spring:
  datasource:
    url: jdbc:mysql://106.12.191.174:3306/User_Information?characterEncoding=utf-8
    username: root
    password: Admin123.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true